### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by GugaGongadze** [reactjs/ka.reactjs.org#2]

**Comment by giiorg** [comment]
როგორც ვთქვით, issue-ების გახსნა არ არის საჭირო იმის გამოსაცხადებლად, რომ ამა და ამ გვერდს ვთარგმნით. საკმარისია pull request გავაკეთოთ, როდესაც გვერდის, თუნდაც, პირველი ვარიანტი გვექნება შესრულებული.
