### ISSUE TITLE
Lifting State Up

### ISSUE THREAD

**Issue by gtsitsvidze** [reactjs/ka.reactjs.org#5]

**Comment by giiorg** [comment]
როგორც ვთქვით, issue-ების გახსნა არ არის საჭირო იმის გამოსაცხადებლად, რომ ამა და ამ გვერდს ვთარგმნით. საკმარისია pull request გავაკეთოთ, როდესაც გვერდის, თუნდაც, პირველი ვარიანტი გვექნება შესრულებული.
