### ISSUE TITLE
ინგლისური ტერმინები სახელობით ბრუნვაში (DOM vs DOM-ი)

### ISSUE THREAD

**Issue by giiorg** [reactjs/ka.reactjs.org#6]
დავუსვათ თუ არა "-ი" ბოლოში სახელობით ბრუნვაში მყოფ ტერმინებს რომლებსაც არ ვთარგმნით და ვტოვებთ ინგლისურად?

მაგალითად, DOM უნდა დავწეროთ თუ DOM-ი?

**Comment by GugaGongadze** [comment]
ჩემს აზრს დავაფიქსირებ, DOM-ი უფრო სწორ ფორმად მიმაჩნია.

ინტერნეტში ვერანაირი წესი ვიპოვე, მსგავს შემთხვევაში როგორ უნდა მოიქცე.

**Comment by giiorg** [comment]
@GugaGongadze საბოლოოდ, ვგონებ, აქ ასე ვთანხმდებით, რომ სახელობითში '-ი'-ის გარეშე დავწეროთ ინგლისურად მოხმობილი ტერმინები. დამიდასტურე და დავხურავ ამ issue-საც.
