### ISSUE TITLE
React vs რეაქტი

### ISSUE THREAD

**Issue by giiorg** [reactjs/ka.reactjs.org#7]
რას ფიქრობთ, "React" ვთარგმნოთ საერთოდ?

**Comment by giiorg** [comment]
აშკარად იქეთკენ ვიხრები, რომ დავტოვოთ როგორც არის - React

**Comment by GugaGongadze** [comment]
მეც უთარგმნელად დატოვება მგონია სწორი.

**Comment by giiorg** [comment]
აქაც ვთანხმედებით, ასე გამოვიყენოთ ხოლმე - React
