### ISSUE TITLE
"React-ის ..." vs "React-..."

### ISSUE THREAD

**Issue by giiorg** [reactjs/ka.reactjs.org#8]
ზოგ კონტექსტში, ვგონებ, აჯობებს "React-ის ..." ამ კონსტრუქციის მაგივრად გამოვიყენოთ ასეთი კონსტრუქცია "React-...", როგორც ეს არის ამ მაგალითებში:

React-ელემენტები (და არა - React-ის ელემენტები)
React-აპლიკაციები (და არა - React-ის აპლიკაციები)

**Comment by GugaGongadze** [comment]
კარგი აზრია.
class component-ი და functional component-იც იმავენაირად ვთარგმნოთ?
კლას-კომპონენტი
ფუნქცია-კომპონენტი

**Comment by giiorg** [comment]
მგონი აქ ვთანხმდებით. თუ ამ ტიპის მსაზღვრელია 'რეაქტული ...' (რეაქტული ელემენტები, მაგალითად) და არა 'რეაქტის ...' გამოვიყენოთ ხოლმე 'React-...' კონსტრუქცია

ვხურავ ამ issue-ს, reopen გაუკეთეთ თუ საჭიროდ ჩათვლით.
